version: '3.8'

services:
  skillup-backend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "${PORT:-5000}:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_POOLED_URL=${DATABASE_POOLED_URL}
    
    # No volume mounts - rebuild container for changes
    # This approach works reliably on Windows
    
    # Override command for development
    command: npm run dev
    
    restart: unless-stopped
    networks:
      - skillup-dev-network

networks:
  skillup-dev-network:
    driver: bridge 